/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.plantastic;

public class MessageUtils {
    private MessageUtils() {
        //no-op
    }
    public static String getMessage() {
        return "Hello      World!";
    }
}
